#! /bin/sh
#
### BEGIN INIT INFO
# Provides:          collorg
# Required-Start:    $all
# Required-Stop:     
# Should-Start:      2 3 4 5
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      
# Short-Description: collorg cache service
# Description:       collorg cache service
### END INIT INFO

PATH=/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=collorg
DESC="Collorg cache service"
DAEMON="/usr/local/bin/cog cache"

RUN=no
RUN_AS_USER=www-data

# Include saned defaults if available
if [ -f /etc/default/collorg ] ; then
    . /etc/default/collorg
fi

COLLORG_APP="$COLLORG_APPS"

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
    for COLLORG_APP in "$COLLORG_APPS"; do
	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
		--exec $DAEMON -- -d $COLLORG_APP start
    done
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
		/usr/bin/skill cog
	echo "$NAME."
	;;
  force-reload)
	# check whether $DAEMON is running. If so, restart
	start-stop-daemon --stop --test --quiet --pidfile \
		/var/run/$NAME.pid --exec $DAEMON \
	&& $0 restart \
	|| exit 0
	;;
  restart)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --oknodo --quiet --pidfile \
		/var/run/$NAME.pid --exec $DAEMON
	sleep 1
	start-stop-daemon --start --quiet --pidfile \
		/var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  status)
	if [ -s /var/run/$NAME.pid ]; then
            RUNNING=$(cat /var/run/$NAME.pid)
            if [ -d /proc/$RUNNING ]; then
                if [ $(readlink /proc/$RUNNING/exe) = $DAEMON ]; then
                    echo "$NAME is running."
                    exit 0
                fi
            fi

            # No such PID, or executables don't match
            echo "$NAME is not running, but pidfile existed."
            rm /var/run/$NAME.pid
            exit 1
        else
            rm -f /var/run/$NAME.pid
            echo "$NAME not running."
            exit 1
        fi
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
