#!/usr/bin/env python
#-*- coding: utf-8 -*-

from collorg.controller.controller import Controller

ctrl = Controller()
db = ctrl.db

def get_fields_names():
    fields_names = []
    for sch in db.schemas:
        for fqtn in list(sch.fqtns):
            table = db.table(fqtn)
            for field in table._cog_fields:
                if not field.name in fields_names:
                    fields_names.append(field.name)
    fields_names.sort()
    return fields_names

def get_actions_labels():
    actions = []
    for action in db.table('collorg.application.action'):
        if action.label_.value and not action.label_.value in actions:
            actions.append(action.label_.value)
    actions.sort()
    return actions

print("""
# This file has been generated by ~/collorg/tools/fields/i18n.py

# Fields names\n""")
for field_name in get_fields_names():
    print('_("{}")'.format(field_name.capitalize().replace("_", " ")))
print("\n# Actions labels\n")
for action_label in get_actions_labels():
    print('_("{}")'.format(action_label.capitalize()))

